# Generated by Django 3.2.11 on 2022-01-16 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='link',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='pathImage',
            field=models.TextField(default=''),
        ),
    ]
