# Generated by Django 3.2.11 on 2022-01-16 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_auto_20220116_1653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='pathImage',
            new_name='imageBase64',
        ),
    ]
